// <auto-generated />
using System;
using System.Collections.Generic;
using Dallal_Backend_v2;
using Dallal_Backend_v2.Entities;
using Dallal_Backend_v2.Entities.Submissions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dallal_Backend_v2
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BuyerListing", b =>
                {
                    b.Property<Guid>("FavoriteListingsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FavoritesId")
                        .HasColumnType("uuid");

                    b.HasKey("FavoriteListingsId", "FavoritesId");

                    b.HasIndex("FavoritesId");

                    b.ToTable("BuyerFavoriteListings", (string)null);
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<LocalizedString>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Details.DetailsDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHiddenInSearch")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<LocalizedString>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<int[]>("PropertyTypes")
                        .HasColumnType("integer[]");

                    b.Property<string>("SearchBehavior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DetailsDefinitions");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Details.DetailsDefinitionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DetailsDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<LocalizedString>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DetailsDefinitionId");

                    b.ToTable("DetailsDefinitionOptions");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaInMetersSq")
                        .HasColumnType("numeric");

                    b.Property<int>("BathroomCount")
                        .HasColumnType("integer");

                    b.Property<int>("BedroomCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("Location")
                        .IsRequired()
                        .HasColumnType("geometry (point)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerContract")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PricePerYear")
                        .HasColumnType("numeric");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RentalContractPeriod")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.ListingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("ListingId");

                    b.HasIndex("OptionId");

                    b.ToTable("ListingDetails");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Submissions.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<SubmissionChange>>("Changes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Users.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Users.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AgencyAddress")
                        .HasColumnType("text");

                    b.Property<string>("AgencyEmail")
                        .HasColumnType("text");

                    b.Property<string>("AgencyLogo")
                        .HasColumnType("text");

                    b.Property<string>("AgencyName")
                        .HasColumnType("text");

                    b.Property<string>("AgencyPhone")
                        .HasColumnType("text");

                    b.Property<string>("AgencyWebsite")
                        .HasColumnType("text");

                    b.Property<List<Document>>("Documents")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brokers");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Users.Buyer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BuyerListing", b =>
                {
                    b.HasOne("Dallal_Backend_v2.Entities.Listing", null)
                        .WithMany()
                        .HasForeignKey("FavoriteListingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dallal_Backend_v2.Entities.Users.Buyer", null)
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Area", b =>
                {
                    b.HasOne("Dallal_Backend_v2.Entities.Area", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Details.DetailsDefinitionOption", b =>
                {
                    b.HasOne("Dallal_Backend_v2.Entities.Details.DetailsDefinition", null)
                        .WithMany("Options")
                        .HasForeignKey("DetailsDefinitionId");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Listing", b =>
                {
                    b.HasOne("Dallal_Backend_v2.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dallal_Backend_v2.Entities.Users.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Broker");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.ListingDetail", b =>
                {
                    b.HasOne("Dallal_Backend_v2.Entities.Details.DetailsDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dallal_Backend_v2.Entities.Listing", null)
                        .WithMany("Details")
                        .HasForeignKey("ListingId");

                    b.HasOne("Dallal_Backend_v2.Entities.Details.DetailsDefinitionOption", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId");

                    b.Navigation("Definition");

                    b.Navigation("Option");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Users.Admin", b =>
                {
                    b.HasOne("Dallal_Backend_v2.Entities.Users.User", null)
                        .WithOne("Admin")
                        .HasForeignKey("Dallal_Backend_v2.Entities.Users.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dallal_Backend_v2.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Users.Broker", b =>
                {
                    b.HasOne("Dallal_Backend_v2.Entities.Users.User", "User")
                        .WithOne("Broker")
                        .HasForeignKey("Dallal_Backend_v2.Entities.Users.Broker", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Users.Buyer", b =>
                {
                    b.HasOne("Dallal_Backend_v2.Entities.Users.User", null)
                        .WithOne("Buyer")
                        .HasForeignKey("Dallal_Backend_v2.Entities.Users.Buyer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Area", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Details.DetailsDefinition", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Listing", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Dallal_Backend_v2.Entities.Users.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Broker");

                    b.Navigation("Buyer");
                });
#pragma warning restore 612, 618
        }
    }
}
